### ISSUE TITLE
[FEATURE REQUEST] github issue/pr AR

### ISSUE THREAD

**Issue by sifte** [The-Coding-Realm/coding-bot-v6#28]
**Describe the solution you'd like**
I would like the bot to send a link when something like `Rapptz/discord.py` is in our message e.g.
```
John: Yo @sifte did you see Rapptz/discord.py#696
Coding Bot V6: https://github.com/Rapptz/discord.py/pull/696 (redirects to issues/696)
Sifte: Not yet, I'll check it later. Thanks!
```

```
Titan: Yo mark! Did you check out Rapptz/discord.py yet?
Coding Bot V6: https://github.com/Rapptz/discord.py
Mark: I'll use it later. Thanks!
```

**Comment by SELECT-stupidity-FROM-discord** [comment]
I don't see any reason to implement this honestly unless we have a specific use for this?

**Comment by flickowoa** [comment]
it cud be a nice quality of life feature

**Comment by Titan-Codes** [comment]
Looks like a nice feature ~~cuz i'm there in the example~~

**Comment by SELECT-stupidity-FROM-discord** [comment]
Added this in the latest commit
